# frontend/Dockerfile

# Nginx'i temel al
FROM nginx:alpine

# index.html ve style.css dosyalarını Nginx'in sunacağı dizine kopyala
COPY index.html /usr/share/nginx/html/
COPY style.css /usr/share/nginx/html/