apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # DEĞİŞİKLİK BURADA: İmaj adını güncelledik
        image: kubernetes-sample-backend:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5000